# Site settings
title: Deepthika Sivaram
description: Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "deepthika-sivaram.github.io" #"localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Deepthika Sivaram
user_description: I am an M.S. Computer Science student at the State University of New York at Buffalo, always seeking new challenges and opportunities to expand my expertise. With over 3 years of experience as a Software Development Engineer at Citicorp, I have honed my skills in developing robust solutions. Currently, I am deeply immersed in the world of AI and machine learning, embracing the complexity of these fields and finding innovative solutions to problems. The transformative potential of AI fuels my passion as I continue to explore and contribute to this exciting frontier.
user_title: MS CS Student @ SUNY Buffalo
email: deepthika.sivaram@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: deepthikasivaram
github_username:  deepthika-sivaram
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

